# Generated by Django 3.2 on 2021-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mess_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
