# Generated by Django 3.2 on 2021-04-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_student_mess_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlaCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meal_time', models.CharField(help_text='b,l,d,m', max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meal_time', models.CharField(help_text='b,l,d,m', max_length=1)),
                ('meal_type', models.CharField(help_text='v,n', max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('meal_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
