# Generated by Django 3.2 on 2021-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20210415_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alacarte',
            name='meal_time',
            field=models.CharField(max_length=10),
        ),
    ]
